### ISSUE TITLE
[BUG] STUCK AT LOGGED-IN.

### ISSUE THREAD

**Issue by ecsstasyyy** [charlesbel/Microsoft-Rewards-Farmer#232] opened 2023-08-01 02:13 UTC
### Before submitting a bug report...

- [ ] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Hello,

I open the program it says logging in normally and then after 5 seconds it says logged in and after that its just stuck there.

Can you please fix this I really need this. Also I would recommend adding proxies so multithreading is possible.

_(this bug has been reported before but it still has been fixed it has been a while since its been reported)_

Thank you.

### Copy and paste your error

[LOGIN] Logging-in...
[LOGIN] Logged-in !

### Screenshot of the bug

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/141098392/813eddc0-8d20-464d-886c-46eed965099a)

### Value of dashboard variable

            MeePortal.Rewards.Clarity.clarityInit(window, document, "clarity", "script", "76hfh21kdi");
            var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level1","activeLevelName":"Level 1","progress":14,"progressMax":500,"levels":[{"key":"Level1","active":true,"name":"Level 1","tasks":[{"text":"Free and included with your Microsoft account","url":null}],"privileges":[{"text":"3 points per Bing Search, up to 30 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"1 point per $1 spent in Microsoft Store, plus earn bonus points on select purchases","url":"//www.microsoftstore.com"},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts","url":null},{"text":"Redeem your points for gift cards, sweepstakes entries, or donate them to charity","url":"/rewards/redeem"}]},{"key":"Level2","active":false,"name":"Level 2","tasks":[{"text":"Earn at least 500 points each month","url":null}],"privileges":[{"text":"3 points per Bing Search, up to 150 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"Level 1 Microsoft Store benefits, plus exclusive Level 2 bonus offers","url":null},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts, with exclusives for Level 2 members","url":null},{"text":"Get up to 10% off when redeeming rewards from Microsoft brands","url":null}]}],"benefitsPromotion":{"benefits":[{"key":"BingSearch","text":"Daily Bing search point limit (3 points per search)*","url":"https://www.bing.com/?FORM=MA1368","helpText":"* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile","supportedLevels":{"level1":"50","level2":"250","level2XBoxGold":"250"}},{"key":"EdgeSearch","text":"Bing search bonus daily cap for Microsoft Edge ","url":"https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1","helpText":null,"supportedLevels":{"level1":"5","level2":"20","level2XBoxGold":"20"}},{"key":"PointsDollarSpent","text":"Points earned per $ spent in Microsoft Store online**","url":"https://www.microsoft.com/store/b/home?rtc=1","helpText":"**Qualifying content only. \u003ca class=\u0027c-hyperlink\u0027 href=\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\u0027\u003eSee more\u003c/a\u003e for details.","supportedLevels":{"level1":"1:1","level2":"10:1","level2XBoxGold":"20:1"}},{"key":"PointsSeeDailyOffers","text":"Points for exploring daily offers","url":"https://account.microsoft.com/rewards","helpText":null,"supportedLevels":{"level1":"","level2":"","level2XBoxGold":""}},{"key":"MemberDiscounts","text":"Access to exclusive member sales and discounts","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"MemberInvites","text":"Occasional surprise invites to exclusive member-only events","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"RedeemOff","text":"Up to 10% off when redeeming from Microsoft brands","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}}],"supportedLevelKeys":["level1","level2","level2XBoxGold"],"supportedLevelTitles":["Level 1","Level 2","Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e"],"supportedLevelTitlesMobile":["Level 1","Level 2","Level 2 +Xbox Live Gold"],"activeLevel":"level1","name":"level_benefits","priority":1,"attributes":{"hidden":"True","benefits":"[{ key: \u0027BingSearch\u0027, text: \u0027Daily Bing search point limit (3 points per search)*\u0027, url: \u0027https://www.bing.com/?FORM=MA1368\u0027, helpText: \u0027* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile\u0027, supportedLevels: { \u0027level1\u0027: \u002750\u0027, \u0027level2\u0027: \u0027250\u0027, level2XBoxGold: \u0027250\u0027 } }, { key: \u0027EdgeSearch\u0027, text: \u0027Bing search bonus daily cap for Microsoft Edge \u0027, url: \u0027https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1\u0027, supportedLevels: { \u0027level1\u0027: \u00275\u0027, \u0027level2\u0027: \u002720\u0027, level2XBoxGold: \u002720\u0027 } }, { key: \u0027PointsDollarSpent\u0027, text: \u0027Points earned per $ spent in Microsoft Store online**\u0027, url: \u0027https://www.microsoft.com/store/b/home?rtc=1\u0027, helpText: \u0027**Qualifying content only. \u003ca class=\\\u0027c-hyperlink\\\u0027 href=\\\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\\\u0027\u003eSee more\u003c/a\u003e for details.\u0027, supportedLevels: { \u0027level1\u0027: \u00271:1\u0027, \u0027level2\u0027: \u002710:1\u0027, level2XBoxGold: \u002720:1\u0027 } }, { key: \u0027PointsSeeDailyOffers\u0027, text: \u0027Points for exploring daily offers\u0027, url: \u0027https://account.microsoft.com/rewards\u0027, supportedLevels: { \u0027level1\u0027: \u0027\u0027, \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberDiscounts\u0027, text: \u0027Access to exclusive member sales and discounts\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }  }, { key: \u0027MemberInvites\u0027, text: \u0027Occasional surprise invites to exclusive member-only events\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}, { key: \u0027RedeemOff\u0027, text: \u0027Up to 10% off when redeeming from Microsoft brands\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}]","supportedLevelKeys":"level1;level2;level2XBoxGold","supportedLevelTitle":"Level 1;Level 2;Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e","levelTitleMobile":"Level 1;Level 2;Level 2 +Xbox Live Gold","activeLevel":"level1","give_eligible":"False","destination":""},"offerId":"","complete":false,"counter":0,"activityProgress":0,"activityProgressMax":0,"pointProgressMax":0,"pointProgress":0,"promotionType":"","promotionSubtype":"","title":"","extBannerTitle":"","titleStyle":"","theme":"","description":"","extBannerDescription":"","descriptionStyle":"","showcaseTitle":"","showcaseDescription":"","imageUrl":"","dynamicImage":"","smallImageUrl":"","backgroundImageUrl":"","showcaseBackgroundImageUrl":"","showcaseBackgroundLargeImageUrl":"","promotionBackgroundLeft":"","promotionBackgroundRight":"","iconUrl":"","animatedIconUrl":"","animatedLargeBackgroundImageUrl":"","destinationUrl":"","linkText":"","hash":"53b28ef7f02a15ccbb5b13e737b1ea7b4998ba9b611090e43e25a4e5f224c0da","activityType":"11","isRecurring":false,"isHidden":true,"isTestOnly":false,"isGiveEligible":false,"level":"","slidesCount":0,"legalText":"","legalLinkText":"","deviceType":""}},"availablePoints":14,"lifetimePoints":14,"lifetimePointsRedeemed":0,"ePuid":"21m2AaIpnpZy5a13Urn65uvU2aQdlZyjGrDtRvX5TNo8WZU2z4spET_UjsiGinOZT4wJjINSdBVl9-Wz2pBOdg","redeemGoal":{"name":null,"price":0,"provider":null,"disabled":false,"category":"","title":"","variableGoalSpecificTitle":"","smallImageUrl":"","mediumImageUrl":"","largeImageUrl":"","largeShowcaseImageUrl":"","description":{"itemGroupText":"","smallText":"","largeText":"","legalText":"","showcaseTitle":"","showcaseDescription":""},"showcase":false,"showcaseInAllCategory":false,"originalPrice":0,"discountedPrice":0,"popular":false,"isTestOnly":false,"groupId":"","inGroup":false,"isDefaultItemInGroup":false,"groupTitle":"","groupImageUrl":"","groupShowcaseImageUrl":"","instantWinGameId":"","instantWinPlayAgainSku":"","isLowInStock":false,"isOutOfStock":false,"getCodeMessage":"","disableEmail":false,"stockMessage":"","comingSoonFlag":false,"isGenericDonation":false,"isVariableRedemptionItem":false,"variableRedemptionItemCurrencySymbol":null,"variableRedemptionItemMin":0,"variableRedemptionItemMax":0,"variableItemConfigPointsToCurrencyConversionRatio":0.0,"isAutoRedeem":false},"counters":{"pcSearch":[{"name":"ENKW_search_global_exp2_level1_PC","priority":5,"attributes":{"layout":"MissionTaskLayout","foreground _color":"#00B294","state":"Default","schemaName":"Rewards.Message","title":"PC search","link_text":"Search and earn","description":"Earn up to 30 points per day, 3 points per search on PC","destination":"https://www.bing.com/news/?form=ml11z9\u0026crea=ml11z9\u0026wt.mc_id=ml11z9\u0026rnoreward=1\u0026rnoreward=1","image":"//az15297.vo.msecnd.net/images/rewards/membercenter/missions/278x180/Search-Bonus-278x180px.jpg","small_image":"//az15297.vo.msecnd.net/images/rewards/membercenter/missions/Mobile/Search-teal-75x75px.png","xboxapp_icon":"//az15297.vo.msecnd.net/images/rewards/xboxapp/75x75/bing_v2.png","xboxapp_modal_header":"Earn points on PC and Xbox search","xboxapp_modal_description":"Earn up to 30 points per day, 3 points per search on PC and Xbox.","xboxapp_modal_primary_link_text":"Search with Microsoft Bing","xboxapp_modal_primary_link_destination":"bing://home?ref=rewardscounter","app_package_family_name":"Microsoft.BingXbox_8wekyb3d8bbwe","xboxapp_modal_image":"http://az15297.vo.msecnd.net/images/rewards/xboxapp/counters/coins.png","answerScenario.Tag":"PCSearch","classification.Tag":"PCSearch","classification.ShowProgress":"True","type":"search","recurring":"true","progress":"6","max":"30","complete":"False","offerid":"WW_search_global_level1_PC","give_eligible":"True"},"offerId":"WW_search_global_level1_PC","complete":false,"counter":0,"activityProgress":0,"activityProgressMax":0,"pointProgressMax":30,"pointProgress":6,"promotionType":"search","promotionSubtype":"","title":"PC search","extBannerTitle":"","titleStyle":"","theme":"","description":"Earn up to 30 points per day, 3 points per search on PC","extBannerDescription":"","descriptionStyle":"","showcaseTitle":"","showcaseDescription":"","imageUrl":"//az15297.vo.msec…

**Comment by udu3324** [comment] 2023-08-01 04:42
Duplicate of #225

**Closed** 2023-08-01 20:25 UTC
Labels: bug
