### ISSUE TITLE
[BUG] list index out of range

### ISSUE THREAD

**Issue by Hasif-bit** [charlesbel/Microsoft-Rewards-Farmer#401] opened 2023-11-15 11:53 UTC
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

it was working fine before this but i dont know what happened but it suddenly stops sending messages to my discord webhook and this error appear

### Copy and paste your error

2023-11-15 19:51:05,990 [ERROR] IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\hasif\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\hasif\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\main.py", line 139, in executeBot
    ) = desktopBrowser.utils.getRemainingSearches()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hasif\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\src\utils.py", line 209, in getRemainingSearches
    + counters["pcSearch"][1]["pointProgress"]
      ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

### Screenshots

-

### Value of dashboard variable

-

**Comment by binhphuon** [comment] 2023-11-19 09:02
Same

**Comment by nicoacu** [comment] 2023-11-21 10:30
I'm kinda newbie so take this with a pinch of salt, but I think the issue is because the "pcSearch" list is now refered as "PCSearch" in the rewards dashboard

In other words, if you modify the [utils.py](src/utils.py) and change every appareance of  "pcSearch" to  "PCSearch", I believe it should be fixed.

https://github.com/charlesbel/Microsoft-Rewards-Farmer/blob/3d79862b3a6ba5cbf5829a1ce7dcdb2696de0bae/src/utils.py#L205C1-L213

**Comment by Infern0Tempest** [comment] 2023-11-28 14:49
> > edit: forget what I said previously, I forked and changed some things and now the script works wonderfully,
> > Take a look (or just clone it if u want) at the changes here: https://github.com/nicoacu/Microsoft-Rewards-Farmer/blob/8dd874c4853e787e754fe5bcf3a69480921de6dd/src/utils.py#L206-L216
> 
> I downloaded your fork and am still getting this error. I renamed my old folder and installed this in to the one it wanted. Went through the install steps. Even force reinstalled the chromedriver. Only thing I moved over from the old folder was the accounts file. Still getting same error.
> 
> I did notice on the MS page, the 20 bonus points for Edge is gone. Is that the issue? I only have 150 for search and 100 for mobile now.

I was having the same error so instead of copying the fork (you said it still gave you the error) I just replaced the utils.py file, and it works (sorta?)
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/89815100/e883ddef-4817-44c4-91a8-d215d9dff99d)

**Comment by icescoop12** [comment] 2023-11-28 20:38
> > edit: forget what I said previously, I forked and changed some things and now the script works wonderfully,
> > Take a look (or just clone it if u want) at the changes here: https://github.com/nicoacu/Microsoft-Rewards-Farmer/blob/8dd874c4853e787e754fe5bcf3a69480921de6dd/src/utils.py#L206-L216
> 
> I downloaded your fork and am still getting this error. I renamed my old folder and installed this in to the one it wanted. Went through the install steps. Even force reinstalled the chromedriver. Only thing I moved over from the old folder was the accounts file. Still getting same error.
> 
> I did notice on the MS page, the 20 bonus points for Edge is gone. Is that the issue? I only have 150 for search and 100 for mobile now.

yes the script needs to be changed as MS changed things no bonus points,is it Utils.py that needs to be changed?

**Comment by Ventec247** [comment] 2023-11-29 00:21
@icescoop12 not a perfect fix by any means but I'm too lazy to understand the code further, so heres a lazy ass fix - on line 203 theres a default searchpoints value of 1, set it to your normal value (probably 3) and it'll do the right number of searches.

**Comment by Lectoid** [comment] 2023-11-29 20:58
> @icescoop12 not a perfect fix by any means but I'm too lazy to understand the code further, so heres a lazy ass fix - on line 203 theres a default searchpoints value of 1, set it to your normal value (probably 3) and it'll do the right number of searches.

If you mean in the utils.py file, this seems to break my instance to the point I have to delete the session files.ffffff

**Comment by Ventec247** [comment] 2023-11-29 21:11
> > @icescoop12 not a perfect fix by any means but I'm too lazy to understand the code further, so heres a lazy ass fix - on line 203 theres a default searchpoints value of 1, set it to your normal value (probably 3) and it'll do the right number of searches.
> 
> If you mean in the utils.py file, this seems to break my instance to the point I have to delete the session files.

That change would be in addition to the changes to the util.py from way up top, it'd only correct the issue with searching too many times not anything else

**Comment by icescoop12** [comment] 2023-11-30 08:44
> @icescoop12 not a perfect fix by any means but I'm too lazy to understand the code further, so heres a lazy ass fix - on line 203 theres a default searchpoints value of 1, set it to your normal value (probably 3) and it'll do the right number of searches.

Thanks ventec247 ,that has fixed the too many searches problems 
Only thing now the bot is a bit sketchy at the moment like hanging on logging in occasionally,time-outs on searching
It’s either my proxy or the new searching setup ms has implemented

**Comment by neve360** [comment] 2023-12-01 18:37
[icescoop12](https://github.com/icescoop12) i fixed the problem of the too many searches in the utils file you need to put this code: `        elif targetDesktop == 90 or targetDesktop >= 170: #i have modified the 55 in 90 so its doing the right math
            # Level 1 or 2 US
            searchPoints = 3`

**Comment by Ventec247** [comment] 2023-12-01 18:46
> [icescoop12](https://github.com/icescoop12)for the too many searches i fixed the problem with changing this(i have modified the 55 in 90 so its doing the right math) of the too many searches in the utils file you need to put this code: `elif targetDesktop == 90 or targetDesktop >= 170: ` ` # Level 1 or 2 US` ` searchPoints = 3 `

Thanks for the proper fix to it :)

**Comment by s327887** [comment] 2023-12-01 23:43
> > > edit: forget what I said previously, I forked and changed some things and now the script works wonderfully,
> > > Take a look (or just clone it if u want) at the changes here: https://github.com/nicoacu/Microsoft-Rewards-Farmer/blob/8dd874c4853e787e754fe5bcf3a69480921de6dd/src/utils.py#L206-L216
> > 
> > 
> > I downloaded your fork and am still getting this error. I renamed my old folder and installed this in to the one it wanted. Went through the install steps. Even force reinstalled the chromedriver. Only thing I moved over from the old folder was the accounts file. Still getting same error.
> > I did notice on the MS page, the 20 bonus points for Edge is gone. Is that the issue? I only have 150 for search and 100 for mobile now.
> 
> yes the script needs to be changed as MS changed things no bonus points for using edge anymore see [THIS](https://www.reddit.com/r/MicrosoftRewards/comments/185uhw5/uk_daily_edge_search_points_removed/) ,Is it Utils.py that needs to be changed?
> 
> p.s nicoacu's utils.py seems to be working but doing too many searches (as mentioned above)its like multiplying them by 3,here in the EU *latest yes I can confirm if you need 90 points it will search 90 times instead of the 30 (required for 3 points a search) for both desktop and mobile something must be broken in the utils.py script or its the new changes by MS @klept0 & @nicoacu can you fix this ,please?

Making this change worked for me, it will do 30 desktop Bing searches and 20 mobile ones for 5 points each.       
`elif targetDesktop == 5 or targetDesktop >= 6:
            # Level 1 or 2 US
            searchPoints = 5`

**Comment by abuudarda** [comment] 2023-12-02 04:55
> > > > edit: forget what I said previously, I forked and changed some things and now the script works wonderfully,
> > > > Take a look (or just clone it if u want) at the changes here: https://github.com/nicoacu/Microsoft-Rewards-Farmer/blob/8dd874c4853e787e754fe5bcf3a69480921de6dd/src/utils.py#L206-L216
> > > 
> > > 
> > > I downloaded your fork and am still getting this error. I renamed my old folder and installed this in to the one it wanted. Went through the install steps. Even force reinstalled the chromedriver. Only thing I moved over from the old folder was the accounts file. Still getting same error.
> > > I did notice on the MS page, the 20 bonus points for Edge is gone. Is that the issue? I only have 150 for search and 100 for mobile now.
> > 
> > 
> > yes the script needs to be changed as MS changed things no bonus points for using edge anymore see [THIS](https://www.reddit.com/r/MicrosoftRewards/comments/185uhw5/uk_daily_edge_search_points_removed/) ,Is it Utils.py that needs to be changed?
> > p.s nicoacu's utils.py seems to be working but doing too many searches (as mentioned above)its like multiplying them by 3,here in the EU *latest yes I can confirm if you need 90 points it will search 90 times instead of the 30 (required for 3 points a search) for both desktop and mobile something must be broken in the utils.py script or its the new changes by MS @klept0 & @nicoacu can you fix this ,please?
> 
> Making this change worked for me, it will do 30 desktop Bing searches and 20 mobile ones for 5 points each.
> 
> ```
>     elif targetDesktop == 5 or targetDesktop >= 6:
>         # Level 1 or 2 US
>         searchPoints = 5`
> ```
> 
> File with all needed changes [here](https://github.com/s327887/new/blob/main/utils.py)

What to do for non US regions where you get 3 points for each search and 30 max searches for pc and 20 for mobile.

**Comment by s327887** [comment] 2023-12-02 12:32
> problem is ,might be newer version of chrome but always gets stuck at login now ?

Close all of your python and chrome processes in task manager and rerun the script, worked for me.

**Closed** 2023-12-02 23:16 UTC
Labels: bug
