### ISSUE TITLE
[Enhancement] Possible to add tasks from XBox mobile app and/or Game Pass Quests?

### ISSUE THREAD

**Issue by slickochet** [charlesbel/Microsoft-Rewards-Farmer#236] opened 2023-08-02 22:28 UTC
As the title suggests.  Possibly a stupid question but thought I'd ask since the Bing app ones are being looked into.

**Comment by charlesbel** [comment] 2023-08-05 10:20
Duplicate of #199

**Closed by charlesbel** 2023-08-05 10:20 UTC

**Comment by slickochet** [comment] 2023-08-05 12:02
I'm talking about a different app. The Xbox app, not the bing one.  As well as Xbox game pass quests.

**Comment by charlesbel** [comment] 2023-08-05 12:07
> I'm talking about a different app. The Xbox app, not the bing one.  As well as Xbox game pass quests.

They require to own or to play game wich is not possible for this bot...

**Comment by EastArctica** [comment] 2023-08-25 13:26
> > I'm talking about a different app. The Xbox app, not the bing one.  As well as Xbox game pass quests.
> 
> They require to own or to play game wich is not possible for this bot...

I know I'm replying to a closed issue but yes, it is possible. Check issue #306 for information on it. However you are right about the Xbox game pass quests. Those likely do require the games themselves and can't be spoofed.

**Comment by slickochet** [comment] 2023-08-25 13:33
Yeah there's definitely things that earn pointscould be done without games like this Jewel, Opening the XBox App.
And the Microsoft Rewards app on XBox consoles can similarly earn points just by visiting the store pages for games or opening the app.
![2023-08-25 14_32_33-Greenshot](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/20989696/e86f6875-420f-4279-9d8b-20cf48a6d120)
![2023-08-25 14_32_43-Greenshot](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/20989696/a85897ac-d1eb-453c-8fd2-5ddefc43e6f5)

**Comment by EastArctica** [comment] 2023-08-25 13:37
> Yeah there's definitely things that earn pointscould be done without games like this Jewel, Opening the XBox App. And the Microsoft Rewards app on XBox consoles can similarly earn points just by visiting the store pages for games or opening the app. ![2023-08-25 14_32_33-Greenshot](https://user-images.githubusercontent.com/20989696/263283641-e86f6875-420f-4279-9d8b-20cf48a6d120.jpg) ![2023-08-25 14_32_43-Greenshot](https://user-images.githubusercontent.com/20989696/263283643-a85897ac-d1eb-453c-8fd2-5ddefc43e6f5.jpg)

Xbox is a massive source of points so it would be great to it something going with that. I have no clue how to reverse it though... We can't really throw a proxy with a root certificate on there... At least based on [this](https://answers.microsoft.com/en-us/xbox/forum/all/adding-a-certificate-to-the-trusted-root/f4e0fb6e-52f8-4531-8d9e-636e2170b4e4)...

**Comment by theskid31** [comment] 2023-08-25 14:13
Hi all
Problem still is with the bot not completing the quiz rewards and polls from the normal pc rewards page
Is anybody on with this fix yet
A may have created a fix for the high cpu usage which I’ll add a fork this weekend for,been testing it last few days and it’s seems to work fine,just the quiz and polls need fixing

**Comment by EastArctica** [comment] 2023-08-25 14:19
> Hi all Problem still is with the bot not completing the quiz rewards and polls from the normal pc rewards page Is anybody on with this fix yet I may have created a fix for the high cpu usage which I’ll add a fork this weekend for,been testing it last few days and it’s seems to work fine,just the quiz and polls need fixing

Please don't post on random issues because you see they're active. Is there an issue that fits this better? I don't quite understand what the issue is. My bot has no issues with completing the quiz rewards/polls from [rewards.bing.com](https://rewards.bing.com). Are you referring to my attached image?

![Screenshot_20230825_101838](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/32211444/3dbace4d-c81e-4d58-9656-e5ea555fcb63)
