### ISSUE TITLE
getting an error 

### ISSUE THREAD

**Issue by corn674** [charlesbel/Microsoft-Rewards-Farmer#241] opened 2023-08-06 20:14 UTC
not sure if its on my end or with ipapi but cant get this one or your older version to run keep getting this 

Traceback (most recent call last):
  File "C:\Users\Bubba\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 6, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi' 

and ive double checked i do have ipapi

**Comment by udu3324** [comment] 2023-08-07 21:02
Duplicate of #81 
Make sure you run main.py with "python main.py", not "pip main.py"

**Closed** 2023-08-09 15:02 UTC

**Comment by MorriCf** [comment] 2023-09-19 10:45
Did everything still didnt get the problem solved 🥺🥺

**Comment by MorriCf** [comment] 2023-09-19 10:47
> Did everything still didnt get the problem solved 🥺🥺

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/111272264/52963dce-e860-4c52-b9ab-31b45a4cc173)
