### ISSUE TITLE
Wrong Chromedriver Version

### ISSUE THREAD

**Issue by evox45** [charlesbel/Microsoft-Rewards-Farmer#300] opened 2023-08-19 17:12 UTC
Tried "pip install selenium --upgrade" Doesnt seem to resolve. 

file "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:2517
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.97
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0064A813+48355]
        (No symbol) [0x005DC4B1]
        (No symbol) [0x004E5358]
        (No symbol) [0x005061AC]
        (No symbol) [0x005006B4]
        (No symbol) [0x00500491]
        (No symbol) [0x00530C55]
        (No symbol) [0x0053093C]
        (No symbol) [0x0052A536]
        (No symbol) [0x005082DC]
        (No symbol) [0x005093DD]
        GetHandleVerifier [0x008AAABD+2539405]
        GetHandleVerifier [0x008EA78F+2800735]
        GetHandleVerifier [0x008E456C+2775612]
        GetHandleVerifier [0x006D51E0+616112]
        (No symbol) [0x005E5F8C]
        (No symbol) [0x005E2328]
        (No symbol) [0x005E240B]
        (No symbol) [0x005D4FF7]
        BaseThreadInitThunk [0x76567D59+25]
        RtlInitializeExceptionChain [0x7751B79B+107]
        RtlClearBits [0x7751B71F+191]

**Comment by charlesbel** [comment] 2023-08-19 17:13
Duplicate of #283

**Closed by charlesbel** 2023-08-19 17:13 UTC
