### ISSUE TITLE
[BUG] 'type' object is not subscriptable

### ISSUE THREAD

**Issue by Lectoid** [charlesbel/Microsoft-Rewards-Farmer#245] opened 2023-08-09 14:22 UTC
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Followed the instructions, added user/pass to the json file and remove .sample. Getting error below.

### Copy and paste your error

C:\Users\--\Downloads\Microsoft-Rewards-Farmer-master>python main.py
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "C:\Users\--\Downloads\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\Users\--\Downloads\Microsoft-Rewards-Farmer-master\src\browser.py", line 11, in <module>
    from src.userAgentGenerator import GenerateUserAgent
  File "C:\Users\--\Downloads\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 9, in <module>
    class GenerateUserAgent:
  File "C:\Users\--\Downloads\Microsoft-Rewards-Farmer-master\src\userAgentGenerator.py", line 41, in GenerateUserAgent
    browserVersions: dict[str, Any] = {}
TypeError: 'type' object is not subscriptable

### Screenshot of the bug

N/A

### Value of dashboard variable

N/A

**Comment by Lectoid** [comment] 2023-08-09 14:27
I ran 'pip install selenium --upgrade' again just to be sure. Got this error at the end.

  Attempting uninstall: selenium
    Found existing installation: selenium 3.141.0
    Uninstalling selenium-3.141.0:
      Successfully uninstalled selenium-3.141.0
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.**
requests 2.24.0 requires urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1, but you have urllib3 2.0.4 which is incompatible.
Successfully installed selenium-4.11.2 urllib3-2.0.4f

**Comment by charlesbel** [comment] 2023-08-09 15:01
duplicate of #234

**Closed by charlesbel** 2023-08-09 15:01 UTC
Labels: bug

**Comment by Lectoid** [comment] 2023-08-09 15:07
Thank you. I saw that, but I didn't realize I still had python 3.8 installed after installing the new one. It's working now
