### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by harunresitc** [charlesbel/Microsoft-Rewards-Farmer#109] opened 2022-08-25 19:53 UTC
TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Andrew1644563** [comment] 2022-08-29 00:50
Did you leave it on for too long? Could also be Selenium just timing out. Do you still have this issue?

**Comment by LuckiestOne23** [comment] 2022-09-04 21:35
As @Andrew1644563 noted, should not be caused by the program itself, more likely due to poor internet connection or anything with selenium. Restart it.

**Comment by FRKFFR** [comment] 2022-09-14 18:54
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment] 2023-07-19 09:04
Fixed with v3.0 #188

**Closed by charlesbel** 2023-07-19 09:04 UTC
