### ISSUE TITLE
[BUG] This version of ChromeDriver only supports Chrome version 114 Current browser version is 116.0.5845.96

### ISSUE THREAD

**Issue by gimmx** [charlesbel/Microsoft-Rewards-Farmer#296] opened 2023-08-18 21:23 UTC
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Release is broken completely now using the undetected_chromedriver method. I've tried on a brand new install of python on Windows and always get the error.

When the script runs, Chrome opens, but then immediately crashes.

### Copy and paste your error

2023-08-18 17:20:36,658 [INFO] Using default request storage
2023-08-18 17:20:36,671 [INFO] Created proxy listening on 127.0.0.1:27707
2023-08-18 17:20:36,672 [INFO] Using undetected_chromedriver
2023-08-18 17:20:37,449 [INFO] patching driver executable C:\Users\dev\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-08-18 17:20:39,308 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:27710
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0024A813+48355]
        (No symbol) [0x001DC4B1]
        (No symbol) [0x000E5358]
        (No symbol) [0x001061AC]
        (No symbol) [0x001006B4]
        (No symbol) [0x00100491]
        (No symbol) [0x00130C55]
        (No symbol) [0x0013093C]
        (No symbol) [0x0012A536]
        (No symbol) [0x001082DC]
        (No symbol) [0x001093DD]
        GetHandleVerifier [0x004AAABD+2539405]
        GetHandleVerifier [0x004EA78F+2800735]
        GetHandleVerifier [0x004E456C+2775612]
        GetHandleVerifier [0x002D51E0+616112]
        (No symbol) [0x001E5F8C]
        (No symbol) [0x001E2328]
        (No symbol) [0x001E240B]
        (No symbol) [0x001D4FF7]
        BaseThreadInitThunk [0x753F00C9+25]
        RtlGetAppContainerNamedObjectPath [0x77167B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77167AEE+238]
        (No symbol) [0x00000000]

Traceback (most recent call last):
  File "C:\Users\dev\Desktop\Desktop Files\Software\Microsoft-Rewards-bot\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\dev\Desktop\Desktop Files\Software\Microsoft-Rewards-bot\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Desktop\Desktop Files\Software\Microsoft-Rewards-bot\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\Desktop\Desktop Files\Software\Microsoft-Rewards-bot\src\browser.py", line 77, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 56, in __init__
    super().__init__(
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dev\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:27710
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96
Stacktrace:
Backtrace:
        GetHandleVerifier [0x0024A813+48355]
        (No symbol) [0x001DC4B1]
        (No symbol) [0x000E5358]
        (No symbol) [0x001061AC]
        (No symbol) [0x001006B4]
        (No symbol) [0x00100491]
        (No symbol) [0x00130C55]
        (No symbol) [0x0013093C]
        (No symbol) [0x0012A536]
        (No symbol) [0x001082DC]
        (No symbol) [0x001093DD]
        GetHandleVerifier [0x004AAABD+2539405]
        GetHandleVerifier [0x004EA78F+2800735]
        GetHandleVerifier [0x004E456C+2775612]
        GetHandleVerifier [0x002D51E0+616112]
        (No symbol) [0x001E5F8C]
        (No symbol) [0x001E2328]
        (No symbol) [0x001E240B]
        (No symbol) [0x001D4FF7]
        BaseThreadInitThunk [0x753F00C9+25]
        RtlGetAppContainerNamedObjectPath [0x77167B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77167AEE+238]
        (No symbol) [0x00000000]

### Screenshots

N/A

### Value of dashboard variable

Never gets to bing.

**Comment by charlesbel** [comment] 2023-08-18 21:47
Duplicate of #283

**Closed by charlesbel** 2023-08-18 21:47 UTC
Labels: bug
